language: objective-c
script:
    - xcodebuild -project ./MSMulticastDelegate/MSMulticastDelegate.xcodeproj -scheme MSMulticastDelegate
    - xcodebuild test -project ./MSMulticastDelegate/MSMulticastDelegate.xcodeproj -scheme MSMulticastDelegate
