language: objective-c
before_install:
    - brew update
    - brew install xctool
script:
    - xctool -project ./MSProxyListener/MSProxyListener.xcodeproj -scheme MSProxyListener
    - xctool test -project ./MSProxyListener/MSProxyListener.xcodeproj -scheme MSProxyListener
